name: Build for Linux & Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-24.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install g++-14
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-14

      - name: Verify G++ version
        run: g++-14 --version

      - name: Compile the project
        working-directory: ./src
        run: make -j all CXX=g++-14

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: jieqi-arena-linux
          path: src/jieqi_arena

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            make

      - name: Compile the project
        working-directory: ./src
        shell: msys2 {0}
        run: make -j all

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: jieqi-arena-windows
          path: src/jieqi_arena.exe